# Generated by Django 4.0.2 on 2022-07-16 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='user',
            name='seperation',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=100, unique=True),
        ),
    ]
